export const blogData = [
  {
    blogCategory: "technolgy",
    blogImageUrl:"https://biotechworldindia.in/wp-content/uploads/2023/04/2020_6largeimg_2125304850.jpeg",
    blogTitleName: "NITian",
    blogDescription: "Information Technology Undergrad at NIT Jalandhar.",
    read_more_route: "technolgy-NITian-blog",
    Contributer_Name: "Ankan Kumar",
    posted_Date: "2024-4-21",
    content: "kuch v likh dete hai",
  },

  {
    blogCategory: "technolgy",
    blogImageUrl:"https://biotechworldindia.in/wp-content/uploads/2023/04/2020_6largeimg_2125304850.jpeg",
    blogTitleName: "tech blog ",
    blogDescription: "collage se hai ",
    read_more_route: "technolgy-blog",
    Contributer_Name: "Ankan Kumar",
    posted_Date: "2024-4-21",
    content: "kuch v likh dete hai",
  },

  {
    blogCategory: "songs_lyric",
    blogImageUrl: "",
    blogTitleName: "tere pyar ne badnam kr diya",
    blogDescription: "dard hota hai hone do ,dil jalta hai ",
    read_more_route: "song-lyrics",
    Contributer_Name: "Ankan Kumar",
    posted_Date: "2024-4-21",
    content: "kuch v likh dete hai",
  },
  {
    blogCategory: " Indian Article",
    blogImageUrl: "",
    blogTitleName: "Article one",
    blogDescription: "Aricle ek me india is bharat ,bharat is india ",
    read_more_route: "article-first",
    Contributer_Name: "Ankan Kumar",
    posted_Date: "2024-4-21",
    content: "kuch v likh dete hai",
  },
  {
    blogCategory: "Indian Article",
    blogImageUrl: "",
    blogTitleName: "Article second ",
    blogDescription: "Article second hai  ye hai ki ",
    read_more_route: "article-second",
    Contributer_Name: "Ankan Kumar",
    posted_Date: "2024-4-21",
    content: "indian article second me ye hai lorem wala av k liye kuch v likh dete hai ,bad me dekhte hai ki kya likhna hai",
  },
  {
    blogCategory: "indian article",
    blogImageUrl: "",
    blogTitleName: "Article third ",
    blogDescription: "Article third hai  ye hai ki ",
    read_more_route: "article-third",
    Contributer_Name: "Ankan Kumar",
    posted_Date: "2024-4-21",
    content: "indian article second me ye hai lorem wala av k liye kuch v likh dete hai ,bad me dekhte hai ki kya likhna hai",
  },
];
