export const mySkillsData=
[
    {   
        mySkilltitle:"C",
        mySkillImage:"https://upload.wikimedia.org/wikipedia/commons/1/19/C_Logo.png",
    },
    {   
        mySkilltitle:"C++",
        mySkillImage:"https://w7.pngwing.com/pngs/46/626/png-transparent-c-logo-the-c-programming-language-computer-icons-computer-programming-source-code-programming-miscellaneous-template-blue.png",
    },
    {   
        mySkilltitle:"JavaScript",
        mySkillImage:"https://logos-world.net/wp-content/uploads/2023/02/JavaScript-Logo.png",
    },
    {   
        mySkilltitle:"Python",
        mySkillImage:"https://logos-world.net/wp-content/uploads/2021/10/Python-Symbol.png",
    },
    {   
        mySkilltitle:"Java",
        mySkillImage:"https://w7.pngwing.com/pngs/34/978/png-transparent-java-object-oriented-jvm-java-logo-applications-web-services-3d-icon-thumbnail.png",
    },
    {   
        mySkilltitle:"HTML",
        mySkillImage:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQPmou6evgeGnMsU4Kac3TEv60q65uqVigxib1NYMmoFw&s",
    },
    {   
        mySkilltitle:"CSS",
        mySkillImage:"https://cdn-icons-png.flaticon.com/512/919/919826.png",
    },
    {   
        mySkilltitle:"Tailwind",
        mySkillImage:"https://cdn.icon-icons.com/icons2/2699/PNG/512/tailwindcss_logo_icon_170649.png",
    },
    {   
        mySkilltitle:"Bootstrap",
        mySkillImage:"https://w7.pngwing.com/pngs/628/224/png-transparent-bootstrap-plain-wordmark-logo-icon.png",
    },
    {   
        mySkilltitle:"SAAS",
        mySkillImage:"https://thumbs.dreamstime.com/b/software-as-service-saas-technology-icon-logo-packaged-software-decentralized-application-cloud-computing-gear-wheels-software-197770968.jpg",
    },
    {   
        mySkilltitle:"Node js",
        mySkillImage:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTejDbnovRWSYR1UFXVPsxRTRjd3fGjobjtJkGb5ZIr0g&s",
    },
    {   
        mySkilltitle:"express",
        mySkillImage:"https://ih1.redbubble.net/image.438908244.6144/st,small,507x507-pad,600x600,f8f8f8.u2.jpg",
    },
    {   
        mySkilltitle:"redux",
        mySkillImage:"https://raw.githubusercontent.com/reduxjs/redux/master/logo/logo.png",
    },
    {   
        mySkilltitle:"jupyter",
        mySkillImage:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7Lf82AbrHTmViq2lWqyJx2goiwZ_Y4B1wY2Vs-zfy0g&s",
    },
    {   
        mySkilltitle:"MONGODB",
        mySkillImage:"https://cdn.worldvectorlogo.com/logos/mongodb-icon-1.svg",
    },
    {   
        mySkilltitle:"mySQL",
        mySkillImage:"https://1000logos.net/wp-content/uploads/2020/08/MySQL-Logo.jpg",
    },
    {   
        mySkilltitle:"Docker",
        mySkillImage:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTOWB0O05kOxw46rsJxGYPtWgV6UrK3RxVE6PEnPYH8Xw&s",
    },
    {   
        mySkilltitle:"ubuntu",
        mySkillImage:"https://c4.wallpaperflare.com/wallpaper/878/379/643/computers-linux-wallpaper-preview.jpg",
    },
    {   
        mySkilltitle:"Linux",
        mySkillImage:"https://e7.pngegg.com/pngimages/342/131/png-clipart-penguin-tux-design-logo-linux-penguin-animals-logo.png",
    },
    {   
        mySkilltitle:"git",
        mySkillImage:"https://logowik.com/content/uploads/images/git6963.jpg",
    },
    {   
        mySkilltitle:"gitHub",
        mySkillImage:"https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png",
    },
    {   
        mySkilltitle:"jira",
        mySkillImage:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSn7ZBau0tASyDh2OJjC4qFVZVOTXT7kHncwQ&usqp=CAU",
    },
    {   
        mySkilltitle:"Selenium",
        mySkillImage:"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Selenium_logo.svg/2560px-Selenium_logo.svg.png",
    },
    {   
        mySkilltitle:"AWS",
        mySkillImage:"https://5.imimg.com/data5/SELLER/Default/2021/8/NP/YN/DN/3775979/aws-logo.png",
    },

]